
[[policies]]
name = "Enable read access for all users"
table = "games"
operation = "SELECT"
definition = """
  true
"""

[[policies]]
name = "Enable insert access for all users"
table = "games"
operation = "INSERT"
definition = """
  true
"""

[[policies]]
name = "Enable update access for all users"
table = "games"
operation = "UPDATE"
definition = """
  true
"""

[[policies]]
name = "Enable delete access for all users"
table = "games"
operation = "DELETE"
definition = """
  true
"""
