// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fxaajscxfjetipaarkwk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ4YWFqc2N4ZmpldGlwYWFya3drIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE1MDI0MzgsImV4cCI6MjA1NzA3ODQzOH0.Xq6LHF4uhWSOHhE_ATcvr8fzXuW5j6CltVLOUwfDA8c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);